<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>LibraryManager.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Entities\Entities.csproj" />
    </ItemGroup>

</Project>
