// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3310f8f9-f4bd-4a88-81fc-d50fdc2bc7dd"),
                            DateOfBirth = new DateTime(1920, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ray Bradbury"
                        },
                        new
                        {
                            Id = new Guid("d6b0b215-9108-493c-985c-1b541a2c92ef"),
                            DateOfBirth = new DateTime(1920, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            Id = new Guid("f16c5009-1386-4be4-a4cc-8944fe7e92c1"),
                            DateOfBirth = new DateTime(1948, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terry Pratchett"
                        });
                });

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4145bbe3-5e1e-4034-9d54-da63f56c02c3"),
                            AuthorId = new Guid("3310f8f9-f4bd-4a88-81fc-d50fdc2bc7dd"),
                            PublishedYear = 1953,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = new Guid("560a5138-59b7-43be-aac4-03056c4a27d8"),
                            AuthorId = new Guid("3310f8f9-f4bd-4a88-81fc-d50fdc2bc7dd"),
                            PublishedYear = 1950,
                            Title = "The Martian Chronicles"
                        },
                        new
                        {
                            Id = new Guid("d6808a67-50c8-493f-b224-3ecc4cabab1b"),
                            AuthorId = new Guid("3310f8f9-f4bd-4a88-81fc-d50fdc2bc7dd"),
                            PublishedYear = 1957,
                            Title = "Dandelion Wine"
                        },
                        new
                        {
                            Id = new Guid("dfc4017b-733e-49b3-b915-0572a729ffa0"),
                            AuthorId = new Guid("d6b0b215-9108-493c-985c-1b541a2c92ef"),
                            PublishedYear = 1950,
                            Title = "I, Robot"
                        },
                        new
                        {
                            Id = new Guid("09820e43-229b-42c6-9f38-39f58bbefb58"),
                            AuthorId = new Guid("d6b0b215-9108-493c-985c-1b541a2c92ef"),
                            PublishedYear = 1951,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = new Guid("4e4a2cf1-6bb3-462c-b8cd-208e9161cb9a"),
                            AuthorId = new Guid("f16c5009-1386-4be4-a4cc-8944fe7e92c1"),
                            PublishedYear = 1983,
                            Title = "The Colour of Magic"
                        },
                        new
                        {
                            Id = new Guid("236187cc-6c1c-48e5-8fc4-6df2976f31ca"),
                            AuthorId = new Guid("f16c5009-1386-4be4-a4cc-8944fe7e92c1"),
                            PublishedYear = 1987,
                            Title = "Mort"
                        });
                });

            modelBuilder.Entity("Entities.Book", b =>
                {
                    b.HasOne("Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
